name: geog_env

channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - statsmodels
  - scikit-learn
  - geopandas
  - shapely
  - fiona
  - pyproj
  - pygeos
  - rtree
  - mapclassify
  - libpysal
  - geopy
  - cartopy
  - pyepsg
  - contextily
  - rasterio
  - geoplot
  - folium
  - packaging


      


